<Project>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/purelogiccode/XISOSharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/purelogiccode/XISOSharp.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryBranch>master</RepositoryBranch>
  </PropertyGroup>

</Project>
