<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Build & Analyzers -->
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.125" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.301" />
    <PackageVersion Include="MinVer" Version="6.0.0" />
    <!-- Test -->
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <!-- Benchmarks -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <!-- XISOSharpTester -->
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="WPF-UI" Version="4.3.0" />
    <PackageVersion Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>
</Project>