<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ExtractXiso</RootNamespace>

        <PackageId>ExtractXiso</PackageId>
        <Version>2.7.1</Version>
        <Authors>in</Authors>
        <Description>A library for creating, extracting, listing, and rewriting Xbox ISO (XISO) images.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>xiso;xbox;iso;extract-xiso</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
